version: '3'

services:
  discovery:
    build:
      context: ./platform-service/discovery/
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8761:8761"
  common:
    build:
      context: ./business-service/common/
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./business-service/common/src/main/resources/config/:/var/app/external

    environment:
      spring.cloud.config.server.git.uri: /var/app/external
  apigateway:
    build:
      context: ./platform-service/api_gateway/
      dockerfile: Dockerfile
    depends_on:
      - discovery
    restart: unless-stopped
    command: sh -c './wait-for discovery:8761 -- java -jar api_gateway.jar'
    ports:
      - "8080:8080"
  one:
    build:
      context: ./business-service/one/
      dockerfile: Dockerfile
    depends_on:
      - discovery
      - common
    restart: unless-stopped
    command: sh -c './wait-for discovery:8761 -- java -jar one.jar'
  two:
    build:
      context: ./business-service/two/
      dockerfile: Dockerfile
    depends_on:
      - discovery
      - common
    restart: unless-stopped
    command: sh -c './wait-for discovery:8761 -- java -jar two.jar'
  three:
    build:
      context: ./business-service/three/
      dockerfile: Dockerfile
    depends_on:
      - discovery
      - common
    restart: unless-stopped
    command: sh -c './wait-for discovery:8761 -- java -jar three.jar'
  two-api:
    build:
      context: ./business-service/two-api/
      dockerfile: Dockerfile
    depends_on:
      - discovery
      - common
    restart: unless-stopped
    command: sh -c './wait-for discovery:8761 -- java -jar two-api.jar'
    ports:
      - "8088:8088"



